### ISSUE TITLE
Add endpoint to search products by titles and other filters

### ISSUE THREAD

**Issue by imranbaig1977** [Shopify/mobile-buy-sdk-android#321] opened 2016-10-25 19:35 UTC
Add endpoint to search products by titles and other filters. 
Please let me know if it already exists.

**Comment by krisorr** [comment] 2016-10-26 02:18
There currently is no endpoint to do search.
Closing, This ticket is a duplicate of #15.

**Closed by krisorr** 2016-10-26 02:18 UTC
