### ISSUE TITLE
BuyClientError empty string for error body

### ISSUE THREAD

**Issue by mravert93** [Shopify/mobile-buy-sdk-android#330] opened 2016-11-10 14:45 UTC
Hi there, after recently upgrading our SDK to the latest version (2.0.2) we have been getting back blank error responses in the BuyClientError when updating the checkout object.  We've encountered this when the user doesn't input a name or state, etc. in their address.

We've put some breakpoints in the BuyClientError and we can see that when the response object is returned it clearly does have the error json in the body but when the method `extractRetrofitErrorBody` is called to grab that data, it is failing.  It looks to be failing with a "java.io.IOException: Content-length and stream length disagree" error.

Any help with this would be greatly appreciated, thanks!

**Comment by krisorr** [comment] 2016-11-10 18:17
@mravert93, I will take a look

**Comment by krisorr** [comment] 2016-11-10 18:29
@mravert93 - would you be able to provide me with a checkout token and/or email address and shop url for one of these failures?
I can look it up in the logs, and try recreating.

**Comment by mravert93** [comment] 2016-11-10 19:59
@krisorr yes of course!  The email for a purchase is michael.ravert@runkeeper.com and checkout token is `d4c71df4b9f93679e28e21edaa214f77`

**Comment by krisorr** [comment] 2016-11-11 15:26
@mravert93 - we did see this error in earlier versions of the library, as per #249.  It should be fixed in version 2.0.1 and up, I will confirm that there was not a regression that we missed.

I took a look in the logs and only see the checkout token d4c71df4b9f93679e28e21edaa214f77 being used once, with a user agent of "Mobile Buy SDK Android/2.0.0/Runkeeper".  
Do you have another example of a checkout that is failing with this error that I can look up?

Thanks

**Comment by mravert93** [comment] 2016-11-11 18:27
Hi @krisorr, hmm I'll double check that we did in fact upgrade to 2.0.2 and get back to you, I thought I verified a couple of days ago that it was

**Comment by mravert93** [comment] 2016-11-11 20:32
Hi @krisorr here is another checkout token that was built with 2.0.2 `0903fb145e6953b53ff0703d8437fa7d`

**Comment by krisorr** [comment] 2016-11-14 14:29
@mravert93 - thanks.

I can reproduce.  The stream for the errorbody is a single read object, which is why we are extracting and storing it as part of the array.  I will look into why this is not working, and patch.

**Comment by mravert93** [comment] 2016-11-14 15:34
@krisorr Awesome, thanks so much for all the help!

**Comment by krisorr** [comment] 2016-11-14 19:29
@mravert93 - I am having issues reproducing this today.  It looks like it is properly returning the string when I call error.getRetrofitErrorBody() on the 2.0.2 branch.
When debugging, are you maybe calling getRetrofitErrorBody at the same time in multiple threads?
Are you running any interceptors, or touching the response body directly when debugging?  As it is a single use stream, if retrofitResponse.errorBody().string() gets called (even by the debugger) it will be consumed and will empty on a second call.

**Comment by mravert93** [comment] 2016-11-15 22:22
@krisorr I'm also seeing this as resolved today, I didn't change anything on our side though so I'm not quite sure what the difference is but we are now currently getting the correct error response.

**Comment by krisorr** [comment] 2016-11-16 14:19
@mravert93 
It may be that the server had a hiccup, and the response json was a bit off.  I will look into it, but for now I am going to close this ticket.
If you see it happen again, please let us know.

**Closed by krisorr** 2016-11-16 14:19 UTC
Labels: in progress

**Comment by mravert93** [comment] 2016-11-16 20:24
@krisorr Okay that sounds good, thanks for the help!
