### ISSUE TITLE
Search API for searching products ( and collections )

### ISSUE THREAD

**Issue by vjirgale** [Shopify/mobile-buy-sdk-android#287] opened 2016-09-19 12:32 UTC
I think, having search API in Mobile SDK to search products ( and/or collections ) would add value.
Can you please provide this support ?

Vinay

( Ref : https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/are-there-any-mobile-sdk-api-for-searching-products-360912#comment-360963 )

**Comment by krisorr** [comment] 2016-09-23 18:45
Closing as duplicate of #15

**Closed by krisorr** 2016-09-23 18:45 UTC
