### ISSUE TITLE
How to get customer orders statues ?

### ISSUE THREAD

**Issue by Midhilaj** [Shopify/mobile-buy-sdk-android#527] opened 2018-02-14 08:32 UTC
https://github.com/Shopify/mobile-buy-sdk-android#customer-orders-
There is no method to getting order statues like canceled  etc

```java
Storefront.QueryRootQuery query = Storefront.query(root -> root
	.customer(tocken, customer -> customer
		.orders(arg -> arg.first(100), connection -> connection
			.edges(edge -> edge
				.node(node -> node
					.processedAt()
					.shippingAddress(mailingaddress->mailingaddress.firstName().lastName().address1())
					.orderNumber()
					.totalShippingPrice()
					.phone()
					.totalPrice()
					.phone()
					.subtotalPrice()
					.lineItems(arg -> arg.first(500),lineItems->lineItems.edges(orderlistiteam->orderlistiteam.node(
							child->child.title().quantity().variant(va->va.price()))))
				)
			)
		)
	)
);
```

**Comment by sav007** [comment] 2018-02-14 10:00
What kind of order status are you looking for? Just canceled?

**Comment by Midhilaj** [comment] 2018-02-16 09:33
No, all order tracking details like approval,processing,shipping,delivery ...

**Comment by schin1207** [comment] 2019-09-05 12:55
> https://github.com/Shopify/mobile-buy-sdk-android#customer-orders-
> There is no method to getting order statues like canceled etc
> 
> ```java
> Storefront.QueryRootQuery query = Storefront.query(root -> root
> 	.customer(tocken, customer -> customer
> 		.orders(arg -> arg.first(100), connection -> connection
> 			.edges(edge -> edge
> 				.node(node -> node
> 					.processedAt()
> 					.shippingAddress(mailingaddress->mailingaddress.firstName().lastName().address1())
> 					.orderNumber()
> 					.totalShippingPrice()
> 					.phone()
> 					.totalPrice()
> 					.phone()
> 					.subtotalPrice()
> 					.lineItems(arg -> arg.first(500),lineItems->lineItems.edges(orderlistiteam->orderlistiteam.node(
> 							child->child.title().quantity().variant(va->va.price()))))
> 				)
> 			)
> 		)
> 	)
> );
> ```

Did you get any solution for order status?
Because I am also implementing this in my app but I did not find any solution yet.
please help me.

**Comment by rebeccajfriedman** [comment] 2019-12-20 20:12
This is a dupe of https://github.com/Shopify/mobile-buy-sdk-android/issues/588, so I'll close this ticket out.

This is currently being worked on. You can explore the unstable Storefront API version to see what it will look like in the meantime.

**Closed by rebeccajfriedman** 2019-12-20 20:12 UTC
Labels: 3.x, api
