### ISSUE TITLE
How to solve NoSuchMethodError .  No static method com_shopify_buy3_Storefront$CollectionQuery$$Lambda

### ISSUE THREAD

**Issue by Midhilaj** [Shopify/mobile-buy-sdk-android#485] opened 2017-11-08 14:14 UTC
FATAL EXCEPTION: main
                                                   Process: com.midhilaj.myapplication, PID: 31458
                                                   java.lang.NoSuchMethodError: No static method com_shopify_buy3_GraphClient$$Lambda$1_lambda$new$0(Ljava/lang/Runnable;)Ljava/lang/Thread; in class Lcom/shopify/buy3/GraphClient; or its super classes (declaration of 'com.shopify.buy3.GraphClient' appears in /data/app/com.midhilaj.myapplication-1/base.apk)
                                                       at com.shopify.buy3.GraphClient$$Lambda$1.newThread(Unknown Source)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:602)
                                                       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:916)
                                                       at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1582)
                                                       at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:313)
                                                       at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
                                                       at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:625)
                                                       at com.shopify.buy3.RealGraphCall.enqueue(RealGraphCall.java:165)
                                                       at com.shopify.buy3.RealGraphCall.enqueue(RealGraphCall.java:149)
                                                       at com.midhilaj.myapplication.MainActivity.onCreate(MainActivity.java:43)
                                                       at android.app.Activity.performCreate(Activity.java:6679)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by waitingFat** [comment] 2017-11-09 08:49
me too across the same question

**Comment by Midhilaj** [comment] 2017-11-09 13:14
We are waiting for your reply @henrytao-me and @sav007

**Comment by sav007** [comment] 2017-11-09 16:39
That means that something wrong the way how the project was compiled.
Is this buy sdk sample project?

**Comment by henrytao-me** [comment] 2017-11-09 16:42
I have looked into it. I tried the same code on new project and it works as normal. Sample app works just fine as well. I believe there are some versioning mismatch in the project configuration that I am still not sure.

**Comment by Midhilaj** [comment] 2017-11-10 03:29
@sav007  It is not a buy sdk sample project

**Comment by waitingFat** [comment] 2017-11-10 03:56
still show the problem after i changed my gradle version and  jdk version same to the sample app.

**Comment by waitingFat** [comment] 2017-11-10 04:12
I found the reason
Probably our JDK configuration problem that result in not supporting labmda expressions
Did you added these lines of codes to your gradle @Midhilaj 

  compileOptions {
       targetCompatibility 1.8
       sourceCompatibility 1.8
  }
       jackOptions{
            enabled true
       }


now  i remove these codes  and changed my  code  in activity:

        Storefront.mutation(mutation -> mutation
//                .customerCreate(input, query -> query
//                        .customer(
//                                 customer -> customer
//                                .id()
//                                .email()
//                                .firstName()
//                                .lastName()
//                        )
//                        .userErrors(userError -> userError
//                                .field()
//                                .message()
//                        )
//                )
//        );

  Storefront.MutationQuery mutations = Storefront.mutation(new Storefront.MutationQueryDefinition() {
            @Override
            public void define(Storefront.MutationQuery _queryBuilder) {
                _queryBuilder.customerCreate(input, new Storefront.CustomerCreatePayloadQueryDefinition() {
                    @Override
                    public void define(Storefront.CustomerCreatePayloadQuery _queryBuilder) {
                        _queryBuilder.customer(new Storefront.CustomerQueryDefinition() {
                            @Override
                            public void define(Storefront.CustomerQuery _queryBuilder) {
                                _queryBuilder.id().firstName().email().lastName();
                            }
                        }).userErrors(new Storefront.UserErrorQueryDefinition() {
                            @Override
                            public void define(Storefront.UserErrorQuery _queryBuilder) {
                                _queryBuilder.field().message();
                            }
                        });
                    }
                });
            }
        });

and  now  it's ok!

**Comment by sav007** [comment] 2017-11-10 15:22
Ok the issues is how you setup you project is not related to the SDK. Closing.

I believe `jackOptions` is the cause.

**Closed by sav007** 2017-11-10 15:22 UTC
